module.exports = {
    all :"SELECT * FROM user",
    all2 :"SELECT * FROM category",
    all3 :"SELECT * FROM content",
    insert : "INSERT INTO `user`(`username`,`password`,`repassword`) VALUES ('value1','value2','value3')" ,
    insert3 :"INSERT INTO `content`(`category`,`title`,`brief`,`content`,`time`,`auther`,`number`) VALUES ('value1','value2','value3','value4',NOW(),'value5','0')",
    insert2 : "INSERT INTO `category`(`name`) VALUES ('value')",
    insert4 : "INSERT INTO `comment` (`category`, `comment`, `username`, `date`) VALUES ('leixing', 'pinglun', 'mingzi', NOW())",
    select : "SELECT * FROM `user` WHERE username='mingzi'",
    select2 : "SELECT `name` FROM `category` WHERE id='index'",
    select3 : "SELECT * FROM `content` WHERE id='index'",
    select4 : "SELECT `isAdmin` FROM `user` WHERE id='index'",
    select5 : "SELECT `comment`,`username`,`date` FROM `comment` WHERE category='index'",
    check : "SELECT * FROM `user` WHERE `username` LIKE 'xingming' AND `password` LIKE 'mima'",
    admin : "SELECT `isAdmin` FROM `user` WHERE username = 'mingzi' ",
    count : "SELECT count(*) from user",
    count2 : "SELECT count(*) from category",
    count3 : "SELECT count(*) from content",
    count4 : "SELECT count(*) from content WHERE category = index",
    count5 : "SELECT count(*) from comment WHERE category = index",
    limit : "SELECT * FROM `user` LIMIT x,y",
    limit2 : "SELECT * FROM `content` WHERE category = fenlei LIMIT key,value",
    update : "UPDATE `category` SET `name` = 'mingzi' WHERE `category`.`id` = 'biaoshi'",
    update2 : "UPDATE `content` SET `category` = 'fenlei',`title` = 'biaoti',`brief` = 'jianjie', `content` = 'neirong',`time` = NOW(),`auther` = 'zuozhe',`number` = '0' WHERE `content`.`id` = 'biaoshi'",
    update3 : "UPDATE `user` SET `isAdmin` = '1' WHERE `user`.`id` = 'biaoshi'",
    update4 : "UPDATE `user` SET `isAdmin` = '0' WHERE `user`.`id` = 'biaoshi'",
    update5 : "UPDATE `content` SET `number` = `number`+1 WHERE `id` = 'index'",
    update6 : "UPDATE `content` SET `comment` = 'pinglun' WHERE `content`.`id` = 'biaoshi'",
    delete : "DELETE FROM `category` WHERE id ='biaoshi' ",
    delete2 : "DELETE FROM `content` WHERE id ='biaoshi' ",
    delete3 : "DELETE FROM `user` WHERE id ='biaoshi'"
};